### ISSUE TITLE
Turn out nested URL permalinks

### ISSUE THREAD

**Issue by michellealiem** [aliemteam/ALiEMU#184] opened 2018-01-08 07:07 UTC
Can we activate this please (assuming it won't break existing code)? https://www.aliemu.com/wp-admin/options-permalink.php

Need more specific permalink names to avoid confusion as we add more content.
![screenshot 2018-01-07 10 08 49](https://user-images.githubusercontent.com/15097022/34661595-8c7a2a74-f3ff-11e7-9824-d1b1dc322d28.png)

**Comment by michellealiem** [comment] 2018-01-08 07:19
Whoops... meant “turn ON nested URL permalinks”

**Comment by dsifford** [comment] 2018-01-08 18:04
Duplicate of #103

**Closed as completed by dsifford** 2018-01-08 18:04 UTC
