### ISSUE TITLE
Format: Certificate box

### ISSUE THREAD

**Issue by ghost** [aliemteam/ALiEMU#79] opened 2016-12-26 15:42 UTC
At completion of AIR and AIR-Pro quiz, "Print Certificate" box needs a white font.
![certificate arrow](https://cloud.githubusercontent.com/assets/7309097/21483903/e2defe66-cb3e-11e6-92c6-7920e7b700d4.png)

**Comment by dsifford** [comment] 2017-01-06 18:27
This looks normal for me. Can't reproduce without a direct url to where the issue lies. 

![image](https://cloud.githubusercontent.com/assets/5240018/21728372/e4adaf20-d413-11e6-8ed7-5b83a8c570f1.png)

**Comment by dsifford** [comment] 2017-01-06 18:28
@michellealiem see above

**Comment by michellealiem** [comment] 2017-01-07 20:34
Found the link: https://www.aliemu.com/quizzes/air-pro-tox-2/ 
![screen shot 2017-01-07 at 12 33 17 pm](https://cloud.githubusercontent.com/assets/15097022/21744970/9066d9a6-d4d5-11e6-9bb8-6b61f06e2aaf.png)

**Comment by michellealiem** [comment] 2017-01-07 21:14
OK going to close this thread because will now be redirected to home page of module, where can print certificate.

**Closed as completed** 2017-01-08 15:16 UTC
